tes3conv.exe -o "merge_add_effects.json" "merge_add_effects.esp"
tes3conv.exe -o "merge_base.json" "merge_base.esp"
tes3conv.exe -o "merge_edit_all.json" "merge_edit_all.esp"
tes3conv.exe -o "merge_minor_tweaks.json" "merge_minor_tweaks.esp"
tes3conv.exe -o "Morrowind.json" "Morrowind.esm"
tes3conv.exe -o "Bob's Diverse Blood.json" "Bob's Diverse Blood.esp"
tes3conv.exe -o "Patch for Purists.json" "Patch for Purists.esm"