tes3conv.exe -o "merge_add_effects.esp" "merge_add_effects.json"
tes3conv.exe -o "merge_base.esp" "merge_base.json"
tes3conv.exe -o "merge_edit_all.esp" "merge_edit_all.json"
tes3conv.exe -o "merge_minor_tweaks.esp" "merge_minor_tweaks.json"
tes3conv.exe -o "Morrowind.esm" "Morrowind.json"
tes3conv.exe -o "Bob's Diverse Blood.esp" "Bob's Diverse Blood.json"
tes3conv.exe -o "Patch for Purists.esm" "Patch for Purists.json"